name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: v
categories:
  - type: pre-exclude
    when:
      label: skip-changelog
  - title: Features
    semver-increment: minor
    exclusive: true
    when:
      label: enhancement
  - title: Bug Fixes
    semver-increment: patch
    exclusive: true
    when:
      label: bug
  - title: Documentation
    semver-increment: patch
    exclusive: true
    when:
      label: documentation
  - title: Maintenance
    semver-increment: patch
  - type: version-resolver
    semver-increment: major
    when:
      label: major
change-template: '- $TITLE (#$NUMBER) $AUTHORS'
change-title-escapes: '\<*_&'
autolabeler:
  - label: enhancement
    branch:
      - '/feat(ure)?\/.+/'
    title:
      - '/^feat(ure)?[:(]/i'
  - label: bug
    branch:
      - '/(bug)?fix\/.+/'
    title:
      - '/^fix[:(]/i'
  - label: documentation
    files:
      - '*.md'
      - 'docs/**/*'
    branch:
      - '/docs?\/.+/'
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_TAG
