[package]
name = "us-hr-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
us-hr-core = { path = "../../crates/us-hr-core", version = "0.1.0" }
us-hr-usb = { path = "../../crates/us-hr-usb", version = "0.1.0" }

[lints]
workspace = true
