[package]
name = "us-hr-control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eframe.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
us-hr-core = { path = "../../crates/us-hr-core", version = "0.1.0" }
us-hr-usb = { path = "../../crates/us-hr-usb", version = "0.1.0" }

[lints]
workspace = true
